- include/handlers.h
- src/handlers.cpp
- src/main.cpp
- src/ut/handlers_test.cpp
I haven't written UTs that create a MockHealthChecker and check it was used correctly - I'll do that at some point. Otherwise, this is complete.
> [Reviewer: Ellie] Integrate health-checking

- src/ut/handlers_test.cpp
These are the two UTs I didn't get round to last week. Should be reasonably self-explanatory.
> [Reviewer: Ellie] Add UTs to check that the health checker is triggered appropriately

- include/call_list_store.h
- src/call_list_store.cpp
- src/main.cpp
- src/ut/call_list_store_test.cpp
- src/ut/mock_call_list_store.h
This PR contains some tweaks to the call list store and it UTs to use the changes cassandra store infrastructure made under Metaswitch/cpp-common#266.
Tested by checking all the existing homestead UTs run.
> [Reviewer: Rob] Co-req changes for sto1173

- debian/memento.init.d
- src/main.cpp
Same as https://github.com/Metaswitch/sprout/pull/1023.
> [No review required]: Make DNS blacklist duration configurable

- debian/memento.postinst
- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_cassandra_plugin.py
This is the memento equivalent of https://github.com/Metaswitch/crest/pull/200. Just in case you wanted to look at it...
> Reviewer RKD: Add memento cluster cassandra plugin

- memento.root/usr/share/clearwater/infrastructure/scripts/memento.monit
Metaswitch/clearwater-monit#16
> [No reviewer] Add in groups

- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_cassandra_plugin.py
- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_remote_memcached_plugin.py
> [No reviewer] Update Memento plugins for GR

- memento.root/etc/cron.hourly/memento_disk_usage
- memento.root/usr/share/clearwater/cassandra-schemas/memento.sh
- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_cassandra_plugin.py
- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_remote_memcached_plugin.py
- memento.root/usr/share/clearwater/infrastructure/scripts/memento.monit
> [Reviewer: Rob] Cass 2.0.14

- debian/memento-nginx.postinst
- memento-nginx.root/usr/share/clearwater/infrastructure/scripts/create-memento-nginx-config
> Reviewer Ellie - Create NGinx site in infrastructure

- memento-nginx.root/usr/share/clearwater/infrastructure/scripts/create-memento-nginx-config
Port of https://github.com/Metaswitch/crest/pull/211
> No review required - Diff against the symlink, not the main file

- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_cassandra_plugin.py
- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_memcached_plugin.py
- memento.root/usr/share/clearwater/clearwater-cluster-manager/plugins/memento_remote_memcached_plugin.py
Co-req change to accompany Metaswitch/clearwater-etcd#70
> [Reviewer: Andy] Enable cassandra clustering to cope with multiple networks

- src/main.cpp
See https://github.com/Metaswitch/ralf/pull/160
> Reviewer MIRW: Set default blacklist duration

- src/call_list_store.cpp
Hi Andy,
This is one of the changes to fix the inconsistencies introduced by the interface change in [this PR](https://github.com/Metaswitch/cpp-common/pull/349). Would you mind reviewing it please?
Thanks,
Tom
> [Reviewer: Andy] Updated calls to ha_get_* to pass sas trail ID

- debian/memento.postinst
Similar changes to https://github.com/Metaswitch/ralf/pull/174
> [No reviewer] Minor fixes for the postinst file

- src/ut/mementoappserver_test.cpp
Includes a small fix - need method to be "BYE" to write a database entry.
Addition to test for coverage.
> Update to UTs to handle ignoring of reinvites

- debian/memento.postinst
- memento-nginx.root/usr/share/clearwater/infrastructure/scripts/create-memento-nginx-config
- memento.root/usr/share/clearwater/infrastructure/scripts/memento
Similar fix to https://github.com/Metaswitch/crest/pull/229
> Check for config before running scripts

- memento.root/usr/share/clearwater/cassandra-schemas/memento.sh
Fix schema creation for https://github.com/Metaswitch/clearwater-cassandra/issues/54
> Fix up schema creation

- memento.root/usr/share/clearwater/infrastructure/scripts/memento
Same as https://github.com/Metaswitch/homestead/pull/270.
> [Reviewer: Ellie] Check that Cassandra is installed before installing schema

- debian/memento.init.d
- src/main.cpp
Merging without review - this is basically identical to Metaswitch/chronos#191.
> [No reviewer] Implement a properly locked pidfile

- debian/memento.init.d
- memento.root/usr/share/clearwater/infrastructure/scripts/memento.monit
> [No reviewer] Move the pidfile into a writeable directory

- memento.root/usr/share/clearwater/cassandra-schemas/memento.sh
Matching changes for https://github.com/Metaswitch/crest/pull/268
> No reviewer: Create GR schema

- memento.root/usr/share/clearwater/infrastructure/alarms/memento_alarms.json
- src/main.cpp
Update to use new communication monitor to raise alarms and logs.
> [No Reviewer] Astaire alarm log updates

- debian/memento.postinst
- debian/memento.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
> [No reviewer] Add alarm triggers

- src/ut/coverage-not-yet
Take out cpp-common files from coverage-not-yet
> [No reviewer] Move cpp-common UTs to cpp-common

- memento.root/usr/share/clearwater/infrastructure/scripts/memento.monit
See clearwater-infrastructure for the new script which this uses.
> [Reviewer Adam] Update memento to use new uptime monitoring.

- memento.root/usr/share/clearwater/cassandra-schemas/memento.sh
- memento.root/usr/share/clearwater/infrastructure/scripts/memento
See https://github.com/Metaswitch/crest/pull/269
> [No reviewer] Bail out of schema scripts if Cassandra is not installed

- debian/memento.init.d
- src/main.cpp
Following the change in https://github.com/Metaswitch/cpp-common/pull/505
> [No reviewer] Use new signal handler start

- src/Makefile
- src/main.cpp
Using the new AlarmManager from https://github.com/Metaswitch/cpp-common/pull/526
> Use the new AlarmManager

- src/main.cpp
Equivalent to https://github.com/Metaswitch/homestead/pull/393
> [Reviewer: Ellie] Use loopback address rather than localhost for cassandra

- memento-cassandra.root/usr/share/clearwater/cassandra-schemas/memento.sh
See https://github.com/Metaswitch/clearwater-issues/issues/2152
> [No reviewer] Connect to local cassandra when adding schemas

- memento.root/usr/share/clearwater/infrastructure/scripts/memento.monit
As per https://github.com/Metaswitch/sprout/pull/1863
> [No reviewer] Don't wait for 6 cycles before killing a process

- src/httpdigestauthenticate.cpp
Update to be in line with typo fix in the sas-client. PR [here](https://github.com/Metaswitch/sas-client/pull/82).
> [Reviewer: CJR] Fixed marker ID typo

- include/homesteadconnection.h
- src/Makefile
- src/homesteadconnection.cpp
- src/main.cpp
- src/ut/fakehomesteadconnection.cpp
- src/ut/homesteadconnection_test.cpp
Seb,
This updates Memento to the new HTTP Request / HTTP Response API.
I've checked that `make full_test` passes.
> [Reviewer: Seb] Update to new HttpRequest/HttpResponse API
